### ISSUE TITLE
fgmask= cv2.absdiff(frame, background)

### ISSUE THREAD

**Issue by rijutawankar** [Grad-CSE2016/Abandoned-Object-Detection#10]
Hi, I am getting this issue..... I resized the image and frame.... still getting this error. cannot figure out what is going wrong.
/home/rijuta/.virtualenvs/OpencCV_Projects/bin/python /snap/pycharm-community/64/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 39483 --file "/media/rijuta/New Volume/OpencCV_Projects/PycharmProjects/abondoned/AbandonedObjectDetection.py"
pydev debugger: process 7573 is connecting

Connected to pydev debugger (build 181.5087.37)
OpenCV(3.4.1) Error: Sizes of input arguments do not match (The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array') in arithm_op, file /io/opencv/modules/core/src/arithm.cpp, line 659
Traceback (most recent call last):
  File "/snap/pycharm-community/64/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/snap/pycharm-community/64/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/snap/pycharm-community/64/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/media/rijuta/New Volume/OpencCV_Projects/PycharmProjects/abondoned/AbandonedObjectDetection.py", line 147, in <module>
    objs = AOD.get_abandoned_objs(frame)
  File "/media/rijuta/New Volume/OpencCV_Projects/PycharmProjects/abondoned/AbandonedObjectDetection.py", line 72, in get_abandoned_objs
    FG = getForegroundMask(frame, self.BG, 70)
  File "/media/rijuta/New Volume/OpencCV_Projects/PycharmProjects/abondoned/aodHelper.py", line 8, in getForegroundMask
    fgmask= cv2.absdiff(frame, background)
cv2.error: OpenCV(3.4.1) /io/opencv/modules/core/src/arithm.cpp:659: error: (-209) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function arithm_op

**Comment by rijutawankar** [comment]
hi, it worked. I just had to resize with the given dimensions.... thanks anyways
